#version 450

#include "utils/utils.glsl"

layout(local_size_x = 1, local_size_y = 1) in;

#define LOW_GRADIENT vec4(0.0, 0.1, 0.2, 0.3)
#define MID_GRADIENT vec4(0.02, 0.2, 0.48, 0.625)
#define HIGH_GRADIENT vec4(0.0, 0.1625, 0.88, 0.98)
#define CLOUDS_AMBIENT_COLOR_TOP (vec3(149., 167., 200.)*(1.5/255.))
#define CLOUDS_AMBIENT_COLOR_BOTTOM (vec3(39., 67., 87.)*(1.5/255.))

// layout(binding = 0) uniform sampler2D in_albedo;
// layout(binding = 1) uniform sampler2D in_depth;

layout(rgba8, binding = 0) writeonly uniform image2D out_texture;

layout(binding = 1) uniform sampler3D in_noise_texture;
layout(binding = 2) uniform sampler2D in_weather_texture;
layout(binding = 3) uniform sampler3D in_worley_texture;

vec3 background_color = vec3(0.5, 0.7, 0.8);
// vec3 background_color = vec3(1.0, 0.0, 0.0);

vec3 cubeMin = vec3(-500.0, 0.0, -500.0);
vec3 cubeMax = vec3(500.0, 100.0, 500.0);

uniform vec3 sun_direction = vec3(0.0, -1.0, 0.0);
uniform float sun_intensity = 1.0;

uniform float ambiant_influence;

uniform vec2 resolution;
// Camera data
uniform vec3 camera_pos;
uniform vec3 up;
uniform vec3 direction;
uniform float fov;

uniform uint detailed_cloud = 0;

// Phase function parameters
uniform float g0 = 0.6;
uniform float g1 = -0.2;
uniform float weight = 0.5;

// Light scattering coeff
uniform float sigma_a = 0.005;
uniform float sigma_s = 0.115;

// Raymarcher parameters
// uniform float step_size;
uniform float min_step_size;
uniform float max_step_size;
uniform float shadow_step_max;
uniform float shadow_step_size;

// Weather manipulation
uniform float power_intensity = 1.0;
uniform float coordinates_scale;

// Multi scattering
uniform float a = 0.5;
uniform float b = 0.5;
uniform float c = 0.5;
uniform float nb_octave = 5;

// Powder intensity
uniform float powder_intensity = 1.0;
uniform uint activate_powder = 0;

float random(vec2 co) {
    return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);
}

vec3 getDirection() {
    vec3 tn = normalize(direction);
    vec3 bn = normalize(cross(direction, up));
    vec3 vn = cross(tn, bn);

    float gx = 0.001 * tan(fov / 2.0);
    float gy = ((resolution.y) / (resolution.x)) * gx;

    vec3 qx = bn * ((2 * gx) / (resolution.x));
    vec3 qy = vn * ((2 * gy) / (resolution.y));
    vec3 p1m = tn * 0.001 - bn * gx - vn * gy;

    vec3 pij = p1m + qx * gl_GlobalInvocationID.x + qy * (resolution.y - gl_GlobalInvocationID.y);
    return normalize(pij);
}

bool intersect_cube(const vec3 ray_origin, const vec3 ray_direction, out float near, out float far) {
    vec3 t_first = (cubeMin - ray_origin) / ray_direction;
    vec3 t_second = (cubeMax - ray_origin) / ray_direction;

    vec3 t0 = min(t_first, t_second);
    vec3 t1 = max(t_first, t_second);

    near = max(max(t0.x, t0.y), t0.z);
    far = min(min(t1.x, t1.y), t1.z);

    return near < far && far > 0.0;
}

vec2 intersect_sphere(const vec3 ray_origin, const vec3 ray_direction, const vec3 center, const float radius) {
    vec3 ray_origin_c = ray_origin - center;
    float a = dot(ray_direction, ray_direction);
    float b = 2 * dot(ray_direction, ray_origin_c);
    float c = dot(ray_origin_c, ray_origin_c) - radius * radius;

    float delta = b * b - 4 * a * c;

    if (delta < 0) {
        return vec2(0.0, 0.0);
    }

    // Computing the square roots
    delta = sqrt(delta);
    float t0 = (-b + delta) / (2 * a);
    float t1 = (-b - delta) / (2 * a);

    if (t0 > t1)
    {
        float tmp = t0;
        t0 = t1;
        t1 = tmp;
    }

    // Handling if we are in the sphere
    return vec2(t0, t1);
}

float beer(float density)
{
    return exp(-density);
}

float powder(float density)
{
    if (activate_powder == 0)
        return 1.0;
    float f = powder_intensity * (1.0 - exp(-density * 3.0));
    return f;
    // return mix(1.0, f, clamp(-cos_theta * 0.5 + 0.5, 0.0, 1.0));
}

// the Henyey-Greenstein phase function
float phase(const float g, const float cos_theta)
{
    float denom = 1 + g * g - 2 * g * cos_theta;

    return 1 / (4 * M_PI) * (1 - g * g) / (denom * sqrt(denom));
}

// We will here use the dual phase function as described in the following paper:
// Hillaire, S´ebastien, “Physically Based Sky, Atmosphere and Cloud Rendering in Frostbite,”
// SIGGRAPH Physically Based Shading in Theory and Practice course, July 2016.
float dual_phase(const float g0, const float g1, const float cos_theta, const float w) {
    return mix(phase(g0, cos_theta), phase(g1, cos_theta), w);
}

float altitude_influence(float height, float altitude)
{
    float low_factor = 1.0 - clamp(altitude * 2.0, 0.0, 1.0);
    float mid_factor = 1.0 - abs(altitude - 0.5) * 2.0;
    float high_factor = clamp(altitude - 0.5, 0.0, 1.0) * 2.0;

    vec4 base_gradient = low_factor * LOW_GRADIENT + mid_factor * MID_GRADIENT + high_factor * HIGH_GRADIENT;
    // if (base_gradient.x == base_gradient.y && base_gradient.y == 0.00)
    // if (base_gradient.y == 0 || (low_factor == 0 && mid_factor == 0 && high_factor == 0))
    //     return 42.3;

    return remap(height, base_gradient.x, base_gradient.y, 0.0, 1.0) * remap(height, base_gradient.z, base_gradient.w, 1.0, 0.0);
}

float eval_density(vec3 position, bool expensive)
{
    position.y = remap(position.y, cubeMin.y, cubeMax.y, 0.0, 1.0);
    position.x = remap(position.x, cubeMin.x, cubeMax.x, 0.0, 1.0);
    position.z = remap(position.z, cubeMin.z, cubeMax.z, 0.0, 1.0);

    vec2 weather_info = pow(texture(in_weather_texture, position.xz).xy, vec2(power_intensity));

    vec4 noise_info = texture(in_noise_texture, position);

    float low_freq_fbm = noise_info.g * 0.625 + noise_info.b * 0.25 + noise_info.a * 0.125;
    float cloud_shape = remap(noise_info.r, -(1.0 - low_freq_fbm), 1.0, 0.0, 1.0);

    float density_grad = altitude_influence(position.y, weather_info.y);
    cloud_shape *= density_grad;

    float coverage = clamp(weather_info.x, 0.0, 1.0) * 0.5f;
    float coverage_cloud = remap(cloud_shape, coverage, 1.0, 0.0, 1.0);
    coverage_cloud *= coverage;
    coverage_cloud *= mix(1.0, 0.0, clamp(position.y / coverage, 0.0, 1.0));

    float final_cloud = coverage_cloud;

    if (detailed_cloud == 1 || expensive)
    {
        // High Freq Noise Scale ? -> We want to mutiply by some factors
        vec3 erode_cloud_noise = texture(in_worley_texture, vec3(position.x, position.y, position.z)).rgb;
        float high_freq_fbm = (erode_cloud_noise.r * 0.625 + erode_cloud_noise.g * 0.25 + erode_cloud_noise.b * 0.125);

        float high_freq_modifier = mix(high_freq_fbm, 1.0 - high_freq_fbm, clamp(position.y * 8.5, 0.0, 1.0));
        final_cloud = remap(coverage_cloud, high_freq_modifier * 0.3, 1.0, 0.0, 1.0);
    }

    return final_cloud;
}

// Compute volumetric shadow as well and the phase function
float shadow_transmittance(const vec3 coord, const vec3 light_dir, float max_value, float step_size)
{
    // It might not be necessary to get the exact necessary amount of step : a heuristic could be used
    float far = 0.0;
    float near = 0.0;
    intersect_cube(coord, light_dir, near, far);

    // local_step_size is currently an heuristic, might be updated in the futur
    int num_steps_light = int(ceil(min(far, max_value) / step_size));
    float tau = 0;
    for (int nl = 0; nl < num_steps_light; nl++)
    {
        float t_nl = step_size * (nl + 0.5);
        vec3 light_sample_pos = coord + light_dir * t_nl;
        tau += eval_density(light_sample_pos, false) * step_size;
    }
    return tau;
}

vec3 compute_sun_color() {
    return vec3(1.0, 1.0, 1.0) * sun_intensity;
}

vec3 integrate(
    const vec3 ray_origin,
    const vec3 ray_direction,
    const float near,
    const float far)
{
    float sigma_t = (sigma_a + sigma_s);
    vec3 scattered_luminance = vec3(0.0, 0.0, 0.0);
    float transmittance = 1.0;

    vec3 sun_color = compute_sun_color();

    // int ns = int(ceil((far - near) / step_size));
    // float local_step_size = (far - near) / float(ns);

    float step_size = max_step_size;
    int empty_count = 0;

    for (float n = near; n < far; n += step_size) {
        float jitter = 0.5; //random(gl_GlobalInvocationID.xy);
        vec3 sample_pos = ray_origin + ray_direction * (n + jitter * step_size);

        bool expensive = (step_size <= min_step_size * 1.2f);
        float density = eval_density(sample_pos, expensive);

        if (density <= 0.001)
        {
            empty_count++;
            if (empty_count >= 10) {
                step_size = max_step_size;
            }
            continue;
        }

        float shadow = shadow_transmittance(sample_pos, sun_direction, shadow_step_max, shadow_step_size);
        float cos_theta = dot(sun_direction, ray_direction);

        float powder_val = powder(density);

        vec3 ambientLight = mix(CLOUDS_AMBIENT_COLOR_BOTTOM, CLOUDS_AMBIENT_COLOR_TOP, remap(sample_pos.y, cubeMin.y, cubeMax.y, 0.0, 1.0));

        // Multi scattering
        for (float N = 0; N < nb_octave; N++) {
            float sigma_s_prime = sigma_s * pow(a, N);
            float sigma_t_prime = sigma_t * pow(b, N);
            float cos_theta_prime = cos_theta * pow(c, N);

            float phase_factor = dual_phase(g0, g1, cos_theta_prime, weight);
            float shadow_val = beer(shadow * sigma_t_prime);

            // Scattering integration, not energy conservative
            scattered_luminance += sun_color *
                    shadow_val *
                    phase_factor *
                    step_size *
                    sigma_s_prime *
                    transmittance *
                    powder_val *
                    density;

            // more energy conservative, but was not able to make it work with powder -> might be because powder is not energy conservative by definition
            // vec3 S = sun_color *
            //         shadow_val *
            //         powder_val *
            //         density *
            //         sigma_s_prime *
            //         phase_factor;
            // float sample_sigma_t = max(0.0000000001, density * sigma_t_prime);
            // vec3 Sint = (S - S * beer(sample_sigma_t * step_size) * powder_val) / sample_sigma_t;
            // scattered_luminance += transmittance * Sint;
        }
        float sample_sigma_t = max(0.0000000001, density * sigma_t);
        scattered_luminance += ambientLight * transmittance * density * ambiant_influence;

        transmittance *= beer(sample_sigma_t * step_size);

        // Added for optimization reasons
        if (transmittance < 0.01)
            break;

        step_size = clamp(mix(max_step_size, min_step_size, density), min_step_size, max_step_size);
    }
    return scattered_luminance + background_color * transmittance;
}

void main() {
    vec3 ray_origin = camera_pos;
    ivec2 coords = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    vec2 tmp = vec2(coords.x, coords.y);
    vec2 uv = tmp / resolution;

    vec3 ray_direction = getDirection();

    float near = 0.0;
    float far = 0.0;

    if (!intersect_cube(ray_origin, ray_direction, near, far))
    {
        return;
    }

    vec3 color = integrate(ray_origin, ray_direction, near, far);

    color = vec3(clamp(color.r, 0.0, 1.0), clamp(color.g, 0.0, 1.0), clamp(color.b, 0.0, 1.0));

    imageStore(out_texture, coords, vec4(color, 1.0));

    return;
}
