#version 450

#include "noise.glsl"

layout(local_size_x = 1, local_size_y = 1) in;

// layout(binding = 0) uniform sampler2D in_albedo;
// layout(binding = 1) uniform sampler2D in_depth;

layout(binding = 0) uniform Data {
    CloudData data;
};

layout(rgba8_snorm, binding = 0) writeonly uniform image2D out_texture;

layout(binding = 1) uniform sampler3D in_noise_texture;
layout(binding = 2) uniform sampler2D in_weather_texture;

vec3 background_color = vec3(0.5, 0.7, 0.8);

vec3 cubeMin = vec3(-1.0, -1.0, -1.0);
vec3 cubeMax = vec3(1.0, 1.0, 1.0);

uniform vec2 resolution;
// Camera data
uniform vec3 up;
uniform vec3 direction;
uniform float fov;

// Sun debug boolean
uniform uint sun_debug;

uniform uint shadow_transmittance_debug;

// Phase function parameters
uniform float g0;
uniform float g1;
uniform float weight;

// Light scattering coeff
uniform float sigma_a;
uniform float sigma_s;

// Raymarcher parameters -> This might be changed ffor optimization reasons
uniform float step_size;

layout(binding = 1) buffer PointLights {
    PointLight point_lights[];
};

vec3 getDirection() {
    vec3 tn = normalize(direction);
    vec3 bn = normalize(cross(direction, up));
    vec3 vn = cross(tn, bn);

    float gx = 0.001 * tan(fov / 2.0);
    float gy = ((resolution.y) / (resolution.x)) * gx;

    vec3 qx = bn * ((2 * gx) / (resolution.x));
    vec3 qy = vn * ((2 * gy) / (resolution.y));
    vec3 p1m = tn * 0.001 - bn * gx - vn * gy;

    vec3 pij = p1m + qx * gl_GlobalInvocationID.x + qy * (resolution.y - gl_GlobalInvocationID.y);
    return normalize(pij);
}

vec2 intersect_cube(const vec3 ray_origin, const vec3 ray_direction) {
    vec3 t_first = (cubeMin - ray_origin) / ray_direction;
    vec3 t_second = (cubeMax - ray_origin) / ray_direction;

    vec3 t0 = min(t_first, t_second);
    vec3 t1 = max(t_first, t_second);

    float t_min = max(max(t0.x, t0.y), t0.z);
    float t_max = min(min(t1.x, t1.y), t1.z);

    if (t_min > t_max || t_max < 0.0) {
        return vec2(0.0, 0.0);
    }

    return vec2(t_min, t_max);
}

vec2 intersect_sphere(const vec3 ray_origin, const vec3 ray_direction, const vec3 center, const float radius) {
    vec3 ray_origin_c = ray_origin - center;
    float a = dot(ray_direction, ray_direction);
    float b = 2 * dot(ray_direction, ray_origin_c);
    float c = dot(ray_origin_c, ray_origin_c) - radius * radius;

    float delta = b * b - 4 * a * c;

    if (delta < 0) {
        return vec2(0.0, 0.0);
    }

    // Computing the square roots
    delta = sqrt(delta);
    float t0 = (-b + delta) / (2 * a);
    float t1 = (-b - delta) / (2 * a);

    if (t0 > t1)
    {
        float tmp = t0;
        t0 = t1;
        t1 = tmp;
    }

    // Handling if we are in the sphere
    return vec2(t0, t1);
}

// the Henyey-Greenstein phase function
float phase(const float g, const float cos_theta)
{
    float denom = 1 + g * g - 2 * g * cos_theta;

    return 1 / (4 * M_PI) * (1 - g * g) / (denom * sqrt(denom));
}

// We will here use the dual phase function as described in the following paper:
// Hillaire, S´ebastien, “Physically Based Sky, Atmosphere and Cloud Rendering in Frostbite,”
// SIGGRAPH Physically Based Shading in Theory and Practice course, July 2016.
float dual_phase(const float g0, const float g1, const float cos_theta, const float w) {
    return mix(phase(g0, cos_theta), phase(g1, cos_theta), w);
}

float eval_density(vec3 position)
{
    position = position_to_normalized(position, cubeMin, cubeMax);
    float ouais = texture(in_weather_texture, position.xz).x;
    if (ouais == 0.0)
        return 0.0;

    return texture(in_noise_texture, position).x;
}

// Compute volumetric shadow as well and the phase function
float shadow_transmittance(const vec3 coord, const vec3 sun_dir, float local_step_size)
{
    vec2 inter_light = intersect_cube(coord, sun_dir);
    float sigma_t = sigma_s + sigma_a;

    // local_step_size is currently an heuristic, might be updated in the futur
    int num_steps_light = int(ceil(inter_light.y / local_step_size));
    float light_step_size = inter_light.y / num_steps_light;
    float tau = 0;
    for (int nl = 0; nl < num_steps_light; nl++)
    {
        float t_nl = light_step_size * (nl + 0.5);
        vec3 light_sample_pos = coord + sun_dir * t_nl;
        tau += eval_density(light_sample_pos) * sigma_t;
    }
    float shadow = exp(-tau * light_step_size);

    if (shadow_transmittance_debug == 1)
    {
        shadow = 1;
    }
    return shadow;
}

vec3 integrate(
    const vec3 ray_origin,
    const vec3 ray_direction,
    const vec2 t)
{
    float sigma_t = (sigma_a + sigma_s);
    vec3 scattered_luminance = vec3(0.0, 0.0, 0.0);
    float transmittance = 1.0;

    int ns = int(ceil((t.y - t.x) / step_size));
    float local_step_size = (t.y - t.x) / float(ns);

    // Not necessary to iterate all the way through for optimization
    for (int n = 0; n < ns; n++) {
        // remember: to avoid jittering, randomize the 0.5
        float tn = t.x + local_step_size * (n + 0.5);
        vec3 sample_pos = ray_origin + ray_direction * tn;

        float density = eval_density(sample_pos);

        if (density == 0)
            continue;

        const vec3 sun_dir = normalize(point_lights[0].position - sample_pos);
        float shadow = shadow_transmittance(sample_pos, sun_dir, local_step_size);

        float cos_theta = dot(sun_dir, ray_direction);
        float phase_factor = dual_phase(g0, g1, cos_theta, weight);

        // Scattering integration, not energy conservative
        // scattered_luminance += point_lights[0].color *
        //         shadow *
        //         phase_factor *
        //         local_step_size *
        //         sigma_s *
        //         transmittance *
        //         density;

        // Improved scattering function
        // We might want to have some light attenuation -> Must see better implementation for the sun
        vec3 S = point_lights[0].color *
                shadow *
                density *
                sigma_s *
                phase_factor;
        float sample_sigma_t = max(0.0000000001, density * sigma_t);
        vec3 Sint = (S - S * exp(-sample_sigma_t * local_step_size)) / sample_sigma_t;
        scattered_luminance += transmittance * Sint;

        transmittance *= exp(-local_step_size * density * sigma_t);

        // Added for optimization reasons
        if (transmittance < 0.01)
            break;
    }
    return scattered_luminance + background_color * transmittance;
}

void main() {
    vec3 ray_origin = data.camera.camera_pos;
    ivec2 coords = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    vec2 tmp = vec2(coords.x, coords.y);
    vec2 uv = tmp / resolution;

    vec3 ray_direction = getDirection();
    vec2 t = intersect_cube(ray_origin, ray_direction);

    vec2 t_debug = vec2(0.0, 0.0);
    if (sun_debug == 1)
        t_debug = intersect_sphere(ray_origin, ray_direction, point_lights[0].position, 0.3);

    if (t.x <= 0.0 && t.y <= 0.0)
    {
        if (sun_debug == 1 && (t_debug.y > 0.0))
        {
            imageStore(out_texture, coords, vec4(1.0, 0.0, 0.0, 1.0));
        }
        return;
    }

    vec3 p1 = ray_origin + ray_direction * t.x;
    vec3 p2 = ray_origin + ray_direction * t.y;

    float travelled_distance = length(p1 - p2);

    vec3 color = integrate(ray_origin, ray_direction, t);
    if (t.y - t.x == 0)
    {
        imageStore(out_texture, coords, vec4(0.0, 1.0, 0.0, 1.0));
        return;
    }

    color = vec3(clamp(color.r, 0.0, 1.0), clamp(color.g, 0.0, 1.0), clamp(color.b, 0.0, 1.0));

    if (sun_debug == 1 && t_debug.y > 0.0)
    {
        if (t_debug.y < t.y && t_debug.x > t.x)
            color = vec3(0.2, 0.0, 0.0);
        else
            color = vec3(0.5, 0.0, 0.0);
    }

    imageStore(out_texture, coords, vec4(color, 1.0));
    return;
}
