#version 450

#include "utils.glsl"
#include "worley3D.glsl"
#include "perlin.glsl"

layout(local_size_x = 1, local_size_y = 1) in;

uniform vec2 resolution;
uniform float z_index = 0;

layout(rgba8_snorm, binding = 0) writeonly uniform image2D out_texture;

#define M_PI 3.1415926535897932384626433832795
#define NB_OCTAV 2

float fbm(vec3 p) {
    float res = 0.0;
    float amp = 1.0;
    float freq = 1.0;

    for (int i = 0; i < NB_OCTAV; i++) { // Adjust number of octaves
        res += amp * noise(p * freq);
        freq *= 2.0;
        amp *= 0.5;
    }

    // vec2 tmp = worley(p, 1.0, false);
    vec2 tmp = vec2(0.0);
    return (tmp.x) + res;
}

float eval_density(
    const vec3 p) {
    float base_density = fbm(p);
    return abs(base_density); // Adjust the noise evaluation as needed
}

// float eval_density(const vec3 p)
// {
//     float freq = 1;
//     float res = (1 + noise(p * freq)) * 0.5;
//     return res;
// }

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    vec2 tmp = vec2(coords.x, coords.y);
    vec2 uv = tmp / resolution;

    vec3 color = vec3(uv.x, uv.y, 1.0);

    imageStore(out_texture, coords, vec4(color, 1.0));
    return;
}
