#version 450

#include "noise.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba8_snorm, binding = 0) writeonly uniform image3D out_noise_texture;
layout(rgba8_snorm, binding = 1) writeonly uniform image2D out_weather_texture;

// size of cloud texture
vec3 resolution = vec3(128, 128, 128);

void main() {
    ivec3 coords = ivec3(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, gl_GlobalInvocationID.z);
    vec3 tmp = vec3(coords.x, coords.y, coords.z);
    // Value in texture 3D
    vec3 uv = tmp / resolution;
    vec3 position = vec3(uv.x, uv.y, uv.z);

    float final = compute_noise(position, vec3(0.0, 0.0, 0.0), vec3(1.0, 1.0, 1.0));

    vec3 color = vec3(final);

    if (gl_GlobalInvocationID.z == 0)
    {
        vec4 result = vec4(0.0, 0.0, 0.0, 1.0);

        float x = position.x - 0.5;
        float y = position.y - 0.5;

        if (x * x + y * y < 0.2 * 0.2)
            result = vec4(1.0, 0.0, 0.0, 1.0);

        imageStore(out_weather_texture, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), result);
    }

    imageStore(out_noise_texture, coords, vec4(color, 1.0));
    return;
}
